#!/bin/bash

# Utworzenie odpowiedniego pliku .gitignore dla projektu .NET
cat > .gitignore << 'EOL'
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates
.DS_Store

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

# Visual Studio cache/options directory
.vs/
.idea/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUNIT
*.VisualState.xml
TestResult.xml

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
**/Properties/launchSettings.json

# ReSharper
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user
EOL

echo "Plik .gitignore utworzony."

# Usunięcie śledzenia niepotrzebnych plików, ale bez usuwania ich z dysku
git rm -r --cached .
echo "Usunięto śledzenie wszystkich plików."

# Ponowne dodanie plików zgodnie z nowym .gitignore
git add .
echo "Ponownie dodano pliki zgodnie z nowym .gitignore."

# Sprawdzenie czy są jakieś zmiany do zacommitowania
if git diff --cached --quiet; then
    echo "Brak zmian do zacommitowania."
else
    # Squash zmian z ostatnim commitem (zapisanie zmian bez tworzenia nowego commita)
    git commit --amend -C HEAD
    echo "Zmiany zostały squashowane z ostatnim commitem."
fi

echo "Operacja zakończona pomyślnie!"
